config/routes.rb
Yomo::Application.routes.draw do
  get "home/index"
  root :to => 'home#index'
  match "/auth/google_login/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]
  get "sessions" => 'sessions#index'
  match "sessions/anaInfo" => "sessions#anaInfo", via: [:get, :post]
  resources :videos, only: [:index, :new, :show, :create]
  get 'contact/new' => 'contact#new'
  post 'contact' => 'contact#create', :as => 'contact'
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
 
  def new
    @message = Message.new
  end
 
  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      # redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
 
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/new.html.erb
<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>